# Display
name: ScrollBoard
author: PYRRH4
description: Scroll your scoreboard !
website: https://www.spigotmc.org/resources/24184/
# Techy
version: 1.6.3
main: be.pyrrh4.scrollboard.ScrollBoard
depend: [PyrCore]
softdepend: [PlaceholderAPI]
commands:
  scrollboard:
    aliases: [scroll]
    description: ScrollBoard's main command
permissions:
  scrollboard.admin:
    default: op
