#----------------------------------------------------------------------------------------------------
# Configuration file for ScrollBoard plugin !
#----------------------------------------------------------------------------------------------------

#----------------------------------------------------------------------------------------------------
# MySQL (for players' scrollboards)
#----------------------------------------------------------------------------------------------------

mysql_enable: false

#----------------------------------------------------------------------------------------------------
# General settings
#----------------------------------------------------------------------------------------------------

# Default scrollboard

default-scrollboard: sample-default

# Scrollboards update delay
# Every X seconds, the plugin will update the scrollboard for every online player

update-delay: 5

#----------------------------------------------------------------------------------------------------
# World scrollboards (will override default)
#----------------------------------------------------------------------------------------------------

worlds: 
  info-world: sample-general-info
  static-world: sample-static

#----------------------------------------------------------------------------------------------------
# Scrolled lines
# Set a value to -1 if you want to instantly go up/down
#----------------------------------------------------------------------------------------------------

scrolled-lines: 
  scroll: 
    up: 2
    down: 2
  jump: 
    up: 5
    down: 2
  click: 
    up: 2
    down: 2

#----------------------------------------------------------------------------------------------------
# Scrollboards list
#----------------------------------------------------------------------------------------------------
# Scrollboards types :
# - SCROLL : When you scroll up/down
# - JUMP : When you jump/sneak
# - CLICK : When you left/right click
#----------------------------------------------------------------------------------------------------

scrollboards: 

# Default (sample)

  sample-default: 
    type: SCROLL
    title: '&a&lA sample scoreboard !'
    separator:
      - '&7                &o(scroll to go down)'
      - '&r    &7---------------------------'
      - &r
    content:
      - &6This is a very simple scoreboard.
      -  
      - &6There are a lot of characters
      - &6on one line, it goes up to 48 !
      -   
      - '&d&ki&r You can use format codes : &d&ki'
      -    
      - &aa
      - &bb
      - &cc
      - &dd
      - &ee
      - &ff
      - &11
      - &22
      - &33
      - &44
      - &55
      - &66
      - &77
      - &88
      - &99
      - &00
      - &oo
      - &mm
      - &ll
      - &nn
      - &kk
      -     
      - '&d&lAwesome, isn''t it ?'

# Static (sample)

  sample-static: 
    type: DEFAULT
    title: '&a&lStatic scoreboard'
    separator: []
    content:
      - &r
      - &aAlso work with static/classic
      - '&ascoreboards ! :D'
